version: '3.3'

services:
  api:
    build: .
    container_name: smartlink-be-api
    command: yarn start
    volumes:
      - ./src:/app/src
    ports:
      - 8888:3000
    networks:
      - smartlink
    env_file:
      - ./.env
  db:
    image: mysql
    container_name: smartlink-be-db
    ports:
      - 3306:3306
    volumes:
      - smartlink-mysql:/var/lib/mysql
    env_file:
      - ./.mysql.env
    networks:
      - smartlink
volumes:
  smartlink-mysql: {}
networks:
  smartlink:
